yii2-app-basic/controllers/CompositoresController.php
<?php

namespace app\controllers;

use app\models\Compositores;
use app\models\db;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * CompositoresController implements the CRUD actions for Compositores model.
 */
class CompositoresController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Compositores models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new db();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Compositores model.
     * @param int $ID ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($ID)
    {
        return $this->render('view', [
            'model' => $this->findModel($ID),
        ]);
    }

    /**
     * Creates a new Compositores model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Compositores();

        $this -> subirfoto($model);
        

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Compositores model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $ID ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($ID)
    {
        $model = $this->findModel($ID);

        $this -> subirfoto($model);

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Compositores model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $ID ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($ID)
    {
        $model =$this->findModel($ID);
        if(file_exists($model->FOTOGRAFIA)){
            
        unlink($model->FOTOGRAFIA);
        }
                
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Compositores model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $ID ID
     * @return Compositores the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($ID)
    {
        if (($model = Compositores::findOne(['ID' => $ID])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    protected function subirfoto(Compositores $model){
        
            if ($model->load($this->request->post()) ) {
                $model -> FOTO = UploadedFile::getInstance($model, 'FOTO');
                if($model->validate()){
                    if($model -> FOTO){
                        
                        if(file_exists($model->FOTOGRAFIA)){
            
                           unlink($model->FOTOGRAFIA);
                        }
                        
                        $rutaFoto='uploads/'.time()."_".$model->FOTO->baseName.".".$model->FOTO->extension;
                        
                        if($model->FOTO->saveAs($rutaFoto)){
                            $model->FOTOGRAFIA=$rutaFoto;
                            
                        }
                    }
                }
                
                
                
                if($model->save(false)){
                    
                    return $this->redirect(['index']);
                }
                
                
            }
    }
}

yii2-app-basic/views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    
    
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <style>
        
     .navbar {
    background: linear-gradient(to bottom, #ffffff, #d3b38c); /* Degradado vertical de blanco a marrón claro */
    border-radius: 10px; /* Puntas redondeadas */
}
        
        .navbar-nav .nav-link {
            font-family: "Times New Roman", Times, serif; /* Tipografía más clásica */
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); /* Sombreado del texto */
        }
    </style>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-light bg-gradient-light',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Inicio', 'url' => ['/site/index'], 'options' => ['class' => 'nav-item']],
            ['label' => 'Compositores', 'url' => ['/compositores/index'], 'options' => ['class' => 'nav-item']],
            ['label' => 'Partituras', 'url' => ['/composiciones/index'], 'options' => ['class' => 'nav-item']],
            ['label' => 'Sobre Nosotros', 'url' => ['/site/about'], 'options' => ['class' => 'nav-item']],
            ['label' => 'Contacto', 'url' => ['/site/contact'], 'options' => ['class' => 'nav-item']],
            //Yii::$app->user->isGuest ? (
                //['label' => 'Login', 'url' => ['/site/login'], 'options' => ['class' => 'nav-item']]
            //) : (
                //'<li class="navbar-text">'
               // . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                //. Html::submitButton(
                 //   'Logout (' . Yii::$app->user->identity->username . ')',
                  //  ['class' => 'btn btn-link logout']
                //)
               // . Html::endForm()
               // . '</li>'
           // )
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; My Company <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>